import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const comforta = Comfortaa({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "To-do list",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comforta.className}>{children}</body>
    </html>
  );
}
